import type { Equipment, EquipmentCategory, EquipmentStatus } from '@/types';

type SeedItem = Omit<Equipment, 'id' | 'createdAt' | 'updatedAt'>;

// loremflickr: keyword-matched, lock makes it deterministic per item
const lf = (kw: string, lock: number) =>
  `https://loremflickr.com/1200/800/${kw}?lock=${lock}`;

export const SEED_EQUIPMENT: SeedItem[] = [
  // ────────────────── ГУСЕНИЧНІ ЕКСКАВАТОРИ ──────────────────
  {
    name: 'Komatsu PC210-11',
    nameUk: 'Гусеничний екскаватор Komatsu PC210-11',
    category: 'excavators' as EquipmentCategory,
    status: 'available' as EquipmentStatus,
    featured: true,
    description:
      'Гусеничний екскаватор Komatsu PC210-11 масою 22 т для земляних робіт та розробки котлованів. Система KOMTRAX для дистанційного моніторингу стану техніки. Паливоефективний двигун SAA6D107E-3 зі зниженим рівнем шуму.',
    images: [lf('excavator,construction', 1), lf('excavator', 51)],
    specs: {
      'Маса': '21 700 кг',
      'Ківш': '0,93 м³',
      'Глибина копання': '6 630 мм',
      'Висота вивантаження': '4 430 мм',
      'Двигун': 'Komatsu SAA6D107E-3',
      'Потужність': '122 кВт / 163 к.с.',
      'Паливний бак': '410 л',
    },
    pricePerDay: 9500,
    pricePerWeek: 55000,
    pricePerMonth: 185000,
  },
  {
    name: 'Caterpillar 320 Next Generation',
    nameUk: 'Гусеничний екскаватор Caterpillar 320',
    category: 'excavators' as EquipmentCategory,
    status: 'available' as EquipmentStatus,
    featured: true,
    description:
      'CAT 320 наступного покоління з системою Cat Grade with ASSIST для точного контролю глибини копання. Двигун Cat C7.1 відповідає EU Stage V. Ідеальний для генерального підряду та інфраструктурних проектів.',
    images: [lf('excavator,caterpillar', 2), lf('excavator,construction', 52)],
    specs: {
      'Маса': '20 500 кг',
      'Ківш': '0,90 м³',
      'Глибина копання': '6 530 мм',
      'Двигун': 'Cat C7.1 ACERT',
      'Потужність': '122 кВт / 163 к.с.',
      'Паливна система': 'Common Rail',
    },
    pricePerDay: 10500,
    pricePerWeek: 60000,
    pricePerMonth: 200000,
  },
  {
    name: 'Volvo EC300E',
    nameUk: 'Гусеничний екскаватор Volvo EC300E',
    category: 'excavators' as EquipmentCategory,
    status: 'available' as EquipmentStatus,
    featured: false,
    description:
      'Важкий гусеничний екскаватор Volvo EC300E масою 30 т для масштабних земляних робіт, кар\'єрних розробок та дорожнього будівництва. Система ECO Mode знижує витрати палива до 10%.',
    images: [lf('excavator,volvo', 3), lf('excavator', 53)],
    specs: {
      'Маса': '30 100 кг',
      'Ківш': '1,40 м³',
      'Глибина копання': '7 250 мм',
      'Двигун': 'Volvo D8J',
      'Потужність': '170 кВт / 228 к.с.',
      'Паливний бак': '550 л',
    },
    pricePerDay: 14000,
    pricePerWeek: 81000,
    pricePerMonth: 270000,
  },
  {
    name: 'Liebherr R 926',
    nameUk: 'Гусеничний екскаватор Liebherr R 926',
    category: 'excavators' as EquipmentCategory,
    status: 'available' as EquipmentStatus,
    featured: false,
    description:
      'Гусеничний екскаватор Liebherr R 926 масою 26 т з потужним двигуном Liebherr D924 TI-E. Підвищена швидкість копання та повороту. Ергономічна кабіна Liebherr з покращеним оглядом та кліматичним контролем.',
    images: [lf('excavator,liebherr', 4), lf('excavator,heavy', 54)],
    specs: {
      'Маса': '26 400 кг',
      'Ківш': '1,20 м³',
      'Глибина копання': '6 900 мм',
      'Двигун': 'Liebherr D924 TI-E',
      'Потужність': '156 кВт / 209 к.с.',
    },
    pricePerDay: 12000,
    pricePerWeek: 69000,
    pricePerMonth: 230000,
  },
  {
    name: 'Hitachi ZX350LC-6',
    nameUk: 'Гусеничний екскаватор Hitachi ZX350LC-6',
    category: 'excavators' as EquipmentCategory,
    status: 'rented' as EquipmentStatus,
    featured: false,
    description:
      'Hitachi ZX350LC-6 — надійний важкий екскаватор для глибокого копання та завантаження. Система HIOS V оптимізує гідравлічний потік під навантаженням. Зносостійкий ківш з бічними різцями.',
    images: [lf('excavator,hitachi', 5), lf('excavator', 55)],
    specs: {
      'Маса': '35 800 кг',
      'Ківш': '1,60 м³',
      'Глибина копання': '7 590 мм',
      'Двигун': 'Isuzu AK-4HK1X',
      'Потужність': '196 кВт / 263 к.с.',
    },
    pricePerDay: 16000,
    pricePerWeek: 92000,
    pricePerMonth: 308000,
  },

  // ────────────────── САМОСКИДИ ──────────────────
  {
    name: 'Volvo FM500 6×4',
    nameUk: 'Самоскид Volvo FM500 6×4',
    category: 'dump_trucks' as EquipmentCategory,
    status: 'available' as EquipmentStatus,
    featured: true,
    description:
      'Самоскид Volvo FM500 з формулою 6×4, вантажопідйомністю 20 т та кузовом 16 м³. Двигун D13K 500 к.с. з I-Shift автоматичною КПП. Система підтримки водія: AEBS, Lane Assist, адаптивний круїз.',
    images: [lf('dump,truck,construction', 6), lf('dump,truck', 56)],
    specs: {
      'Вантажопідйомність': '20 000 кг',
      'Об\'єм кузова': '16 м³',
      'Двигун': 'Volvo D13K',
      'Потужність': '368 кВт / 500 к.с.',
      'Коробка передач': 'Volvo I-Shift АКП',
      'Осьова формула': '6×4',
    },
    pricePerDay: 6500,
    pricePerWeek: 37000,
    pricePerMonth: 125000,
  },
  {
    name: 'MAN TGS 33.480 6×4',
    nameUk: 'Самоскид MAN TGS 33.480 6×4',
    category: 'dump_trucks' as EquipmentCategory,
    status: 'available' as EquipmentStatus,
    featured: false,
    description:
      'Надійний самоскид MAN TGS 33.480 з кузовом 15 м³. Ергономічна кабіна XL, система TipMatic для автоматичного перемикання. Оптимальний для будівельних майданчиків та кар\'єрів.',
    images: [lf('dump,truck,man', 7), lf('truck,construction', 57)],
    specs: {
      'Вантажопідйомність': '18 000 кг',
      'Об\'єм кузова': '15 м³',
      'Двигун': 'MAN D2676 LF Euro 6',
      'Потужність': '353 кВт / 480 к.с.',
      'Коробка передач': 'ZF TipMatic',
      'Осьова формула': '6×4',
    },
    pricePerDay: 5800,
    pricePerWeek: 33000,
    pricePerMonth: 110000,
  },
  {
    name: 'Scania R500 XT 8×4',
    nameUk: 'Самоскид Scania R500 XT 8×4',
    category: 'dump_trucks' as EquipmentCategory,
    status: 'available' as EquipmentStatus,
    featured: false,
    description:
      'Важкий самоскид Scania R500 XT з формулою 8×4 для перевезення 25 т. Кузов 18 м³ з підігрівом, сталевий настил. Системи ABS, ESP, Hill Start Aid.',
    images: [lf('scania,truck', 8), lf('dump,truck', 58)],
    specs: {
      'Вантажопідйомність': '25 000 кг',
      'Об\'єм кузова': '18 м³',
      'Двигун': 'Scania DC13 Euro 6',
      'Потужність': '368 кВт / 500 к.с.',
      'Осьова формула': '8×4',
    },
    pricePerDay: 8200,
    pricePerWeek: 47000,
    pricePerMonth: 158000,
  },
  {
    name: 'Mercedes-Benz Arocs 3351 6×4',
    nameUk: 'Самоскид Mercedes-Benz Arocs 3351',
    category: 'dump_trucks' as EquipmentCategory,
    status: 'available' as EquipmentStatus,
    featured: false,
    description:
      'Самоскид Mercedes-Benz Arocs 3351 з кузовом 14 м³ та вантажопідйомністю 18 т. Потужний двигун OM 473 LA Euro 6, PowerShift 3 автоматична КПП. Підвищений кліренс для роботи в умовах бездоріжжя.',
    images: [lf('mercedes,truck', 9), lf('dump,truck,heavy', 59)],
    specs: {
      'Вантажопідйомність': '18 500 кг',
      'Об\'єм кузова': '14 м³',
      'Двигун': 'Mercedes-Benz OM 473 LA',
      'Потужність': '370 кВт / 503 к.с.',
      'Осьова формула': '6×4',
    },
    pricePerDay: 6200,
    pricePerWeek: 35000,
    pricePerMonth: 117000,
  },

  // ────────────────── МІНІ-ЕКСКАВАТОРИ ──────────────────
  {
    name: 'Kubota U36-4',
    nameUk: 'Міні-екскаватор Kubota U36-4',
    category: 'mini_excavators' as EquipmentCategory,
    status: 'available' as EquipmentStatus,
    featured: true,
    description:
      'Компактний міні-екскаватор Kubota U36-4 масою 3,6 т з нульовим хвостовим звисом — ідеальний для роботи у дворах, підвалах та вузьких провулках. Двигун Kubota V2607, 3 гідравлічні контури.',
    images: [lf('mini,excavator', 10), lf('compact,excavator', 60)],
    specs: {
      'Маса': '3 630 кг',
      'Ківш': '0,10 м³',
      'Глибина копання': '3 570 мм',
      'Двигун': 'Kubota V2607',
      'Потужність': '19,3 кВт / 26,2 к.с.',
      'Ширина': '1 490 мм',
    },
    pricePerDay: 3200,
    pricePerWeek: 18500,
    pricePerMonth: 62000,
  },
  {
    name: 'Komatsu PC55MR-5',
    nameUk: 'Міні-екскаватор Komatsu PC55MR-5',
    category: 'mini_excavators' as EquipmentCategory,
    status: 'available' as EquipmentStatus,
    featured: false,
    description:
      'Міні-екскаватор Komatsu PC55MR-5 масою 5,4 т з мінімальним радіусом розвороту. Система KOMTRAX для моніторингу стану у реальному часі. Широкий вибір насадок для різних видів робіт.',
    images: [lf('mini,excavator,komatsu', 11), lf('compact,excavator', 61)],
    specs: {
      'Маса': '5 430 кг',
      'Ківш': '0,18 м³',
      'Глибина копання': '3 820 мм',
      'Двигун': 'Komatsu S4D95LE-3',
      'Потужність': '27 кВт / 36 к.с.',
      'Ширина': '1 840 мм',
    },
    pricePerDay: 3800,
    pricePerWeek: 22000,
    pricePerMonth: 73000,
  },
  {
    name: 'JCB 85Z-1',
    nameUk: 'Міні-екскаватор JCB 85Z-1',
    category: 'mini_excavators' as EquipmentCategory,
    status: 'available' as EquipmentStatus,
    featured: false,
    description:
      'Міні-екскаватор JCB 85Z-1 масою 8,5 т — найпотужніший у класі. Нульовий задній звіс, 3 режими роботи (Power, Smart, Eco). Легко транспортується на причепі без спецдозволів.',
    images: [lf('jcb,excavator', 12), lf('mini,excavator', 62)],
    specs: {
      'Маса': '8 500 кг',
      'Ківш': '0,31 м³',
      'Глибина копання': '5 000 мм',
      'Двигун': 'JCB EcoMax',
      'Потужність': '48,5 кВт / 65 к.с.',
      'Ширина': '2 370 мм',
    },
    pricePerDay: 4500,
    pricePerWeek: 26000,
    pricePerMonth: 88000,
  },
  {
    name: 'Bobcat E35',
    nameUk: 'Міні-екскаватор Bobcat E35',
    category: 'mini_excavators' as EquipmentCategory,
    status: 'available' as EquipmentStatus,
    featured: false,
    description:
      'Міні-екскаватор Bobcat E35 масою 3,5 т з покращеною продуктивністю гідросистеми. Навісне обладнання Bobcat сумісне з більш ніж 40 типами насадок. Зручний для трубопровідних та ландшафтних робіт.',
    images: [lf('bobcat,excavator', 13), lf('mini,excavator', 63)],
    specs: {
      'Маса': '3 540 кг',
      'Ківш': '0,09 м³',
      'Глибина копання': '3 430 мм',
      'Двигун': 'Kubota V2607-CR-T',
      'Потужність': '21,3 кВт / 28,6 к.с.',
      'Ширина': '1 480 мм',
    },
    pricePerDay: 3000,
    pricePerWeek: 17000,
    pricePerMonth: 57000,
  },

  // ────────────────── НАВАНТАЖУВАЧІ ──────────────────
  {
    name: 'Caterpillar 950M',
    nameUk: 'Колісний навантажувач Caterpillar 950M',
    category: 'loaders' as EquipmentCategory,
    status: 'available' as EquipmentStatus,
    featured: true,
    description:
      'Колісний навантажувач CAT 950M з ківшом 3,1 м³ та потужністю 154 кВт. Система Cat Payload для точного дозування завантаження. Ідеальний для перевантаження ґрунту, щебеню, піску.',
    images: [lf('wheel,loader,construction', 14), lf('loader,caterpillar', 64)],
    specs: {
      'Маса': '19 600 кг',
      'Ківш': '3,1 м³',
      'Вантажопідйомність': '9 120 кг',
      'Двигун': 'Cat C7.1 ACERT',
      'Потужність': '154 кВт / 207 к.с.',
      'Швидкість': '40 км/год',
    },
    pricePerDay: 7800,
    pricePerWeek: 45000,
    pricePerMonth: 150000,
  },
  {
    name: 'Komatsu WA380-8',
    nameUk: 'Колісний навантажувач Komatsu WA380-8',
    category: 'loaders' as EquipmentCategory,
    status: 'available' as EquipmentStatus,
    featured: false,
    description:
      'Колісний навантажувач Komatsu WA380-8 з інтелектуальною трансмісією KTEC. Система KOMTRAX для дистанційного моніторингу. Знижене споживання палива на 15% порівняно з попереднім поколінням.',
    images: [lf('wheel,loader,komatsu', 15), lf('loader,construction', 65)],
    specs: {
      'Маса': '17 600 кг',
      'Ківш': '2,8 м³',
      'Вантажопідйомність': '7 500 кг',
      'Двигун': 'Komatsu SAA6D107E-3',
      'Потужність': '140 кВт / 188 к.с.',
    },
    pricePerDay: 7200,
    pricePerWeek: 41000,
    pricePerMonth: 138000,
  },
  {
    name: 'Volvo L90H',
    nameUk: 'Колісний навантажувач Volvo L90H',
    category: 'loaders' as EquipmentCategory,
    status: 'available' as EquipmentStatus,
    featured: false,
    description:
      'Volvo L90H — середній колісний навантажувач з ківшом 2,7 м³. Система Boom Suspension System гасить коливання при русі, підвищуючи безпеку та швидкість транспортування. Двигун Volvo D6J відповідає Stage V.',
    images: [lf('volvo,loader', 16), lf('wheel,loader', 66)],
    specs: {
      'Маса': '16 500 кг',
      'Ківш': '2,7 м³',
      'Вантажопідйомність': '7 000 кг',
      'Двигун': 'Volvo D6J',
      'Потужність': '135 кВт / 181 к.с.',
    },
    pricePerDay: 6800,
    pricePerWeek: 39000,
    pricePerMonth: 130000,
  },

  // ────────────────── ТЕЛЕСКОПІЧНІ НАВАНТАЖУВАЧІ ──────────────────
  {
    name: 'JCB 535-140',
    nameUk: 'Телескопічний навантажувач JCB 535-140',
    category: 'telehandlers' as EquipmentCategory,
    status: 'available' as EquipmentStatus,
    featured: true,
    description:
      'Телескопічний навантажувач JCB 535-140 з висотою підйому 14 м та вантажопідйомністю 3,5 т. Широкий вибір змінних насадок: вила, ківш, люлька. Незамінний для монтажних та фасадних робіт.',
    images: [lf('telehandler,jcb', 17), lf('telehandler,construction', 67)],
    specs: {
      'Вантажопідйомність': '3 500 кг',
      'Висота підйому': '14 000 мм',
      'Виліт стріли': '9 900 мм',
      'Двигун': 'JCB EcoMax T4F',
      'Потужність': '55 кВт / 74 к.с.',
      'Маса': '9 900 кг',
    },
    pricePerDay: 6200,
    pricePerWeek: 36000,
    pricePerMonth: 120000,
  },
  {
    name: 'Manitou MLT 741-120',
    nameUk: 'Телескопічний навантажувач Manitou MLT 741-120',
    category: 'telehandlers' as EquipmentCategory,
    status: 'available' as EquipmentStatus,
    featured: false,
    description:
      'Manitou MLT 741-120 — компактний телескопічний навантажувач з висотою підйому 7 м та вантажопідйомністю 4,1 т. Оптимальний для майданчиків з обмеженим простором та сільськогосподарських робіт.',
    images: [lf('manitou,telehandler', 18), lf('telehandler', 68)],
    specs: {
      'Вантажопідйомність': '4 100 кг',
      'Висота підйому': '7 000 мм',
      'Двигун': 'Perkins 1104D-44TA',
      'Потужність': '74,5 кВт / 100 к.с.',
    },
    pricePerDay: 5500,
    pricePerWeek: 32000,
    pricePerMonth: 107000,
  },
  {
    name: 'Liebherr TL 432-13',
    nameUk: 'Телескопічний навантажувач Liebherr TL 432-13',
    category: 'telehandlers' as EquipmentCategory,
    status: 'available' as EquipmentStatus,
    featured: false,
    description:
      'Liebherr TL 432-13 з висотою підйому 13 м та вантажопідйомністю 3,2 т. Стабілізована стріла Triplex, роздільне керування функціями підйому та нахилу. Система LiDAT для моніторингу роботи.',
    images: [lf('liebherr,telehandler', 19), lf('telehandler,crane', 69)],
    specs: {
      'Вантажопідйомність': '3 200 кг',
      'Висота підйому': '13 000 мм',
      'Виліт стріли': '9 200 мм',
      'Двигун': 'Liebherr D934',
      'Потужність': '90 кВт / 121 к.с.',
    },
    pricePerDay: 5800,
    pricePerWeek: 33000,
    pricePerMonth: 112000,
  },

  // ────────────────── БУЛЬДОЗЕРИ ──────────────────
  {
    name: 'Caterpillar D6T XL',
    nameUk: 'Бульдозер Caterpillar D6T XL',
    category: 'bulldozers' as EquipmentCategory,
    status: 'available' as EquipmentStatus,
    featured: true,
    description:
      'Бульдозер Caterpillar D6T XL масою 20 т для планування, зрізання та переміщення ґрунту. Система Cat GRADE з GPS-керуванням відвалом. Двигун Cat C9.3B відповідає EU Stage V.',
    images: [lf('bulldozer,caterpillar', 20), lf('bulldozer,construction', 70)],
    specs: {
      'Маса': '19 600 кг',
      'Відвал': 'XL — 4,36 м',
      'Глибина розпушування': '600 мм',
      'Двигун': 'Cat C9.3B ACERT',
      'Потужність': '164 кВт / 220 к.с.',
      'Тип підвіски': 'High Drive',
    },
    pricePerDay: 11000,
    pricePerWeek: 63000,
    pricePerMonth: 210000,
  },
  {
    name: 'Komatsu D65EX-18',
    nameUk: 'Бульдозер Komatsu D65EX-18',
    category: 'bulldozers' as EquipmentCategory,
    status: 'available' as EquipmentStatus,
    featured: false,
    description:
      'Бульдозер Komatsu D65EX-18 масою 18,9 т з гідравлічним відвалом та розпушувачем. Паливоефективний двигун SAA6D114E-6 з системою автоматичного зниження обертів на холостому ходу.',
    images: [lf('bulldozer,komatsu', 21), lf('bulldozer', 71)],
    specs: {
      'Маса': '18 930 кг',
      'Відвал': '4,12 м × 1,27 м',
      'Двигун': 'Komatsu SAA6D114E-6',
      'Потужність': '160 кВт / 215 к.с.',
      'Паливний бак': '400 л',
    },
    pricePerDay: 9800,
    pricePerWeek: 56000,
    pricePerMonth: 188000,
  },
  {
    name: 'John Deere 850L',
    nameUk: 'Бульдозер John Deere 850L',
    category: 'bulldozers' as EquipmentCategory,
    status: 'available' as EquipmentStatus,
    featured: false,
    description:
      'Бульдозер John Deere 850L масою 16 т з гідростатичною трансмісією PowerShift. Відвал полусферичний VPAT для рівняння поверхні. Збільшений паливний бак 454 л для тривалої безперервної роботи.',
    images: [lf('bulldozer,deere', 22), lf('bulldozer,heavy', 72)],
    specs: {
      'Маса': '16 200 кг',
      'Відвал': '4,08 м',
      'Двигун': 'John Deere PowerTech PSS 6090',
      'Потужність': '130 кВт / 174 к.с.',
      'Паливний бак': '454 л',
    },
    pricePerDay: 8800,
    pricePerWeek: 50000,
    pricePerMonth: 168000,
  },

  // ────────────────── АВТОКРАНИ ──────────────────
  {
    name: 'Grove GMK3050L',
    nameUk: 'Автокран Grove GMK3050L 50 т',
    category: 'cranes' as EquipmentCategory,
    status: 'available' as EquipmentStatus,
    featured: true,
    description:
      'Мобільний автокран Grove GMK3050L вантажопідйомністю 50 т та основною стрілою 50 м. Технологія TWIN-LOCK для надійного кріплення секцій стріли. Незамінний для монтажу металоконструкцій та підйому обладнання.',
    images: [lf('mobile,crane,construction', 23), lf('crane,heavy,lift', 73)],
    specs: {
      'Вантажопідйомність': '50 000 кг',
      'Довжина стріли': '50 м',
      'Виліт': '48 м',
      'Двигун': 'Mercedes-Benz OM501 LA',
      'Осьова формула': '6×4×4',
      'Ширина аутригерів': '7,5 м',
    },
    pricePerDay: 22000,
    pricePerWeek: 126000,
    pricePerMonth: 420000,
  },
  {
    name: 'Liebherr LTM 1050-3.1',
    nameUk: 'Автокран Liebherr LTM 1050-3.1 50 т',
    category: 'cranes' as EquipmentCategory,
    status: 'available' as EquipmentStatus,
    featured: false,
    description:
      'Всьохідний автокран Liebherr LTM 1050-3.1 вантажопідйомністю 50 т. Телескопічна стріла TELEMATIK 38 м з гуськом до 17 м. Гідравлічне шасі з незалежною підвіскою всіх осей.',
    images: [lf('liebherr,crane', 24), lf('mobile,crane', 74)],
    specs: {
      'Вантажопідйомність': '50 000 кг',
      'Довжина стріли': '38 м',
      'З гуськом': '38 + 17 м',
      'Двигун': 'Liebherr D946 A7',
      'Осьова формула': '8×8×8',
    },
    pricePerDay: 25000,
    pricePerWeek: 143000,
    pricePerMonth: 480000,
  },
  {
    name: 'Tadano ATF 90G-4',
    nameUk: 'Автокран Tadano ATF 90G-4 90 т',
    category: 'cranes' as EquipmentCategory,
    status: 'available' as EquipmentStatus,
    featured: false,
    description:
      'Потужний автокран Tadano ATF 90G-4 вантажопідйомністю 90 т для важких підйомів. Стріла 60 м + гусак 31 м. Система AML-C для автоматичного контролю навантаження з попередженням про перевантаження.',
    images: [lf('tadano,crane', 25), lf('heavy,crane,lift', 75)],
    specs: {
      'Вантажопідйомність': '90 000 кг',
      'Довжина стріли': '60 м',
      'З гуськом': '60 + 31 м',
      'Двигун': 'Mercedes-Benz OM 936',
      'Осьова формула': '8×8×8',
    },
    pricePerDay: 38000,
    pricePerWeek: 218000,
    pricePerMonth: 730000,
  },

  // ────────────────── КАТКИ ──────────────────
  {
    name: 'BOMAG BW 213 D-5',
    nameUk: 'Ґрунтовий каток BOMAG BW 213 D-5',
    category: 'compactors' as EquipmentCategory,
    status: 'available' as EquipmentStatus,
    featured: false,
    description:
      'Ґрунтовий вібраційний каток BOMAG BW 213 D-5 масою 13 т з вальцем 2,1 м. Технологія BOMAG ECONOMIZER визначає ступінь ущільнення ґрунту в реальному часі та запобігає надлишковому ущільненню.',
    images: [lf('road,roller,compactor', 26), lf('soil,compactor', 76)],
    specs: {
      'Маса': '13 200 кг',
      'Ширина вальця': '2 130 мм',
      'Частота вібрації': '28 / 33 Гц',
      'Двигун': 'Deutz TCD 3.6',
      'Потужність': '90 кВт / 121 к.с.',
    },
    pricePerDay: 5200,
    pricePerWeek: 30000,
    pricePerMonth: 100000,
  },
  {
    name: 'Hamm HD 130 VO',
    nameUk: 'Асфальтовий каток Hamm HD 130 VO',
    category: 'compactors' as EquipmentCategory,
    status: 'available' as EquipmentStatus,
    featured: false,
    description:
      'Тандемний асфальтовий каток Hamm HD 130 VO масою 13 т для ущільнення асфальтобетонних покриттів. Обидва вальці вібруючі з незалежним регулюванням. Система HCQ Navigation для документування ущільнення.',
    images: [lf('asphalt,roller,road', 27), lf('road,compactor', 77)],
    specs: {
      'Маса': '13 000 кг',
      'Ширина': '2 000 мм',
      'Тип вальців': 'Тандемні вібруючі',
      'Двигун': 'Deutz TCD 3.6 L4',
      'Потужність': '88 кВт / 118 к.с.',
    },
    pricePerDay: 4800,
    pricePerWeek: 27500,
    pricePerMonth: 92000,
  },
  {
    name: 'Caterpillar CB64B',
    nameUk: 'Асфальтовий каток Caterpillar CB64B',
    category: 'compactors' as EquipmentCategory,
    status: 'available' as EquipmentStatus,
    featured: false,
    description:
      'Тандемний асфальтовий каток CAT CB64B масою 6,4 т для дрібних і середніх дорожніх робіт. Вальці 1 270 мм зі зрошенням для запобігання прилипанню асфальту. Система ущільнення CCS для документування результатів.',
    images: [lf('caterpillar,roller', 28), lf('asphalt,road,construction', 78)],
    specs: {
      'Маса': '6 400 кг',
      'Ширина': '1 270 мм',
      'Тип': 'Тандемний',
      'Двигун': 'Cat C3.6',
      'Потужність': '44,7 кВт / 60 к.с.',
    },
    pricePerDay: 3600,
    pricePerWeek: 21000,
    pricePerMonth: 70000,
  },

  // ────────────────── ІНША ТЕХНІКА ──────────────────
  {
    name: 'Atlas Copco ROC D7',
    nameUk: 'Бурова установка Atlas Copco ROC D7',
    category: 'other' as EquipmentCategory,
    status: 'available' as EquipmentStatus,
    featured: false,
    description:
      'Колісна бурова установка Atlas Copco ROC D7 для пневмоударного та обертального буріння. Глибина буріння до 40 м, діаметр до 115 мм. Автоматизована система буріння COP Logic мінімізує вплив людського чинника.',
    images: [lf('drilling,construction', 29), lf('drill,rig,construction', 79)],
    specs: {
      'Глибина буріння': '40 м',
      'Діаметр свердловини': '64–115 мм',
      'Тип буріння': 'Пневмоударне / обертальне',
      'Двигун': 'Cummins QSB6.7',
      'Потужність': '168 кВт / 225 к.с.',
    },
    pricePerDay: 18000,
    pricePerWeek: 103000,
    pricePerMonth: 345000,
  },
  {
    name: 'Wirtgen W 200i',
    nameUk: 'Холодна фреза Wirtgen W 200i',
    category: 'other' as EquipmentCategory,
    status: 'available' as EquipmentStatus,
    featured: false,
    description:
      'Великогабаритна холодна фреза Wirtgen W 200i шириною фрезерування 2 м для знімання асфальтних покриттів. Система LEVEL PRO ACTIVE для автоматичного горизонтального рівняння та управління поперечним ухилом.',
    images: [lf('road,milling,machine', 30), lf('asphalt,milling', 80)],
    specs: {
      'Ширина фрезерування': '2 000 мм',
      'Глибина фрезерування': '330 мм',
      'Двигун': 'Cummins QSX15',
      'Потужність': '708 кВт / 950 к.с.',
      'Продуктивність': 'до 1 000 т/год',
    },
    pricePerDay: 28000,
    pricePerWeek: 160000,
    pricePerMonth: 540000,
  },
];
